// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB9EX4_7nF-vjB-JU_dDSeV9_gYTetiERs',
    appId: '1:625536460867:web:a20d2d9f144d2fa2738cf6',
    messagingSenderId: '625536460867',
    projectId: 'petshopcat-c0c1f',
    authDomain: 'petshopcat-c0c1f.firebaseapp.com',
    storageBucket: 'petshopcat-c0c1f.firebasestorage.app',
    measurementId: 'G-48TJM8VVJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALxPCjgqM_Pxbd8QJ9TCcG5WbvAGKvDus',
    appId: '1:625536460867:android:d9b478975fc504e6738cf6',
    messagingSenderId: '625536460867',
    projectId: 'petshopcat-c0c1f',
    storageBucket: 'petshopcat-c0c1f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAioE6Wk686eTlkVtU84Ex4XL1duwppYTc',
    appId: '1:625536460867:ios:02d8fe7d6157737e738cf6',
    messagingSenderId: '625536460867',
    projectId: 'petshopcat-c0c1f',
    storageBucket: 'petshopcat-c0c1f.firebasestorage.app',
    iosBundleId: 'com.example.petshopcat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAioE6Wk686eTlkVtU84Ex4XL1duwppYTc',
    appId: '1:625536460867:ios:02d8fe7d6157737e738cf6',
    messagingSenderId: '625536460867',
    projectId: 'petshopcat-c0c1f',
    storageBucket: 'petshopcat-c0c1f.firebasestorage.app',
    iosBundleId: 'com.example.petshopcat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB9EX4_7nF-vjB-JU_dDSeV9_gYTetiERs',
    appId: '1:625536460867:web:c0dbf9c89fb7259b738cf6',
    messagingSenderId: '625536460867',
    projectId: 'petshopcat-c0c1f',
    authDomain: 'petshopcat-c0c1f.firebaseapp.com',
    storageBucket: 'petshopcat-c0c1f.firebasestorage.app',
    measurementId: 'G-GTTV6SRWEX',
  );
}
